### ISSUE TITLE
Update Avrdude to 6.2

### ISSUE THREAD

**Issue by karlbackstrom** [arduino/toolchain-avr#17]
Would it be possible to ask for an update to Avrdude 6.1 (from 6.0.1)? All the current patches seems to apply quite cleanly and there are some features in 6.1 that would be great to have for external platforms (especially the flip2 programmer for Xmega chips).

**Comment by PeterVH** [comment]
+1 for the upgrade. It will help ArduinoISP: 6.1 implements some clever fixes that make it possible to program high addresses (over 128KB) with the stk500v1 protocol (which is what ArduinoISP uses). This makes it possible to reliably burn the bootloader of an atmega2560 using ArduinoISP.

**Comment by gh-megabit** [comment]
:+1: against this, too. In particular, AVRdude 6.1 adds support for Atmel-ICE, the current-generation Atmel ISP device.

**Comment by matthijskooijman** [comment]
6.2 has been released by now, too.

**Comment by Testato** [comment]
+1

ArduinoISP fir bootloading the Mega is a very old problem, finally avrdude 6.1 sokve the problem.
And the AtmelICE support is also important

After avrdude update will be possible official insert AtmelICE programmer in the IDE

**Comment by ffissore** [comment]
I'm working on avrdude 6.2

**Comment by facchinm** [comment]
avrdude 6.2 is affected by [this](https://lists.gnu.org/archive/html/avrdude-dev/2015-12/msg00004.html) bug, dropping the update until it gets fixed

**Comment by NicoHood** [comment]
Could you also apply this patch then:
https://github.com/arduino/Arduino/issues/3645

I still dont have an avrdude account. I tried to contact atmel 3 times about 16u2 datasheet faults, but they do not respond (or the wrong person answers). They just dont want to fix the datasheet. But that should not keep us from fixing avrdude, so could anyone post this information to joerg wunsch?

**Comment by gh-megabit** [comment]
I've found avrdude 6.1 and 6.2 to be unreliable with my Atmel-ice - and that's after dealing with the LibUSB filter mess. It might be better to look at another tool for this programmer - atprogram is proving reliable and is easy to enable for uploads. The burn bootloader option may need code changes. I'm not sure if this utility is available on OS X or Linux.

**Comment by facchinm** [comment]
AFAIK `atprogram` only runs on Windows, not a big deal. `avrdude 6.1` works great with Atmel-ICE (tested) and will be integrated in the IDE as soon as we update it officially

**Comment by PaoloP74** [comment]
Can you publish a version 1.6.7-R1?

**Comment by PaoloP74** [comment]
AVRdude **6.3** is out.
--> http://mirror.lihnidos.org/GNU/savannah//avrdude/avrdude-doc-6.3.pdf

**Comment by cmaglie** [comment]
Avrdude 6.3 build scripts are now on their own repository:

https://github.com/arduino/avrdude-build-script
