### ISSUE TITLE
Avrdude on Linux64 is compiled whitout libusb

### ISSUE THREAD

**Issue by ffissore** [arduino/toolchain-avr#23]
_From @eni23 on April 9, 2015 20:5_

arduino: 1.6.3 release from arduino-website
os: debian wheezy amd64

the avrdude-binary is not compiled with libusb, which means no usb-serial adapters are supported.   since most arduino-boards depend on usb-communication this is a quite big impact. 
workaround: compile avrdude 6.0.1 on your own and replace broken binary's

_Copied from original issue: arduino/Arduino#2952_

**Comment by ffissore** [comment]
_From @mschlenker on April 10, 2015 6:57_

USB serial adapters usually are supported by the linux kernels drivers, not userland drivers. Those userland drivers are usually just needed for more exotic programmers. 

Could you please post the USB IDs of the USB serial adapter (lsusb output) and the kernel version you are using (uname -a). Then after plugging in the usb serial adapter take a look at the last lines in the out put of dmesg.

**Comment by ffissore** [comment]
_From @matthijskooijman on April 10, 2015 7:15_

Agreed that libusb isn't needed for usb-serial adapaters, but not having libusb is still a problem for non-serial programmers like the JTAGICE3 and some others.

**Comment by ffissore** [comment]
I've checked the logs, and indeed since we switched to static compiling, avrdude is not linking to libusb anymore. Problem is without static, gcc fails with a missing LTO plugin.

**Comment by eni23** [comment]
u i was a little bit in a hurry i meant isp programmers and not uart-adapters. but anyway, it should be possible to compile it static with libusb..

**Comment by tdicola** [comment]
If it helps, here's a similar issue I raised about this where USBtinyISP programming (for boards like Trinket, Gemma, or the real USBtinyISP programmer) doesn't work because of the static link missing libusb issue: https://github.com/arduino/toolchain-avr/issues/22

**Comment by larsemil** [comment]
Yes. programming Gemma is not possible with 1.6.3.

`avrdude was compiled without usb support.`

**Comment by ffissore** [comment]
Working on this atm

**Comment by ffissore** [comment]
Tag https://github.com/arduino/toolchain-avr/releases/tag/avr-gcc-4.8.1-avrdude-6.0.1-arduino4 should fix it

**Comment by ffissore** [comment]
Sent too early: an updated toolchain will be soon released

**Comment by matthijskooijman** [comment]
What Arduino IDE will this upodated toolchain be released in? 1.6.4 I presume?

**Comment by ffissore** [comment]
Thanks to boards manager, we are going to release a 1.6.4 avr core very soon. May be even tomorrow CET morning

**Comment by ffissore** [comment]
1.6.4 core and tools (with libusb fix) available through boards manager

**Comment by shimanyi** [comment]
@ffissore Any quick fixes on this? I am embarrassingly new in this, I get the error mentioned /bin/avrdude: not found but I can't get any fixes on this. Please give me pointers. I just need to upload from sublime.

Thanks

**Comment by ffissore** [comment]
@shimanyi your issue has nothing to do with this one. This is about missing support to libusb. Your issue is about a non existent /bin/avrdude

**Comment by shimanyi** [comment]
@ffissore Thanks for the feedback, how do I get around that though?

**Comment by ffissore** [comment]
I don't know. It's an issue with stino

**Comment by shimanyi** [comment]
Ok, thanks. Will keep looking.
