### ISSUE TITLE
Upgrade to Atmel AVR GNU Toolchain 3.5.0

### ISSUE THREAD

**Issue by ffissore** [arduino/toolchain-avr#26]
Featuring binutils 2.25 and GCC 4.9.2

**Comment by PaoloP74** [comment]
Atmel AVR GNU Toolchain **3.5.1** available.
--> http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORWINDOWS.aspx
--> http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORLINUX.aspx

**Comment by PaoloP74** [comment]
Atmel AVR GNU Toolchain **3.5.2** available.

**Comment by cmaglie** [comment]
Toolchain has been upgraded to 3.5.3.
