### ISSUE TITLE
Host binaries on a reliable server

### ISSUE THREAD

**Issue by NicoHood** [arduino/toolchain-avr#30]
https://github.com/arduino/toolchain-avr/blob/master/gcc.build.bash#L46

```
+ [[ ! -f mpc-0.9.tar.gz ]]
+ wget http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz
--2016-01-17 23:24:18--  http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz
Resolving www.multiprecision.org (www.multiprecision.org)... 46.30.212.205
Connecting to www.multiprecision.org (www.multiprecision.org)|46.30.212.205|:80... connected.
HTTP request sent, awaiting response... 404 Not Found
2016-01-17 23:24:18 ERROR 404: Not Found.
```

The file is still available here. A checksum would be nice if someone still has this file somewhere. In the fix I'd also add the checksum, if we download from a not trustworthy site.
* http://www.filewatcher.com/m/mpc-0.9.tar.gz.565953-1.html
* http://pkgs.fedoraproject.org/repo/pkgs/libmpc/mpc-0.9.tar.gz/0d6acab8d214bd7d1fbbc593e83dd00d/
* https://dev.openwrt.org/ticket/11299
* https://web.archive.org/web/*/http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz
* aka https://web.archive.org/web/20151124231334/http://www.multiprecision.org/mpc/download/mpc-0.9.tar.gz

**Comment by NicoHood** [comment]
I used the waybackmachine's download and the toolchain compiled fine again.

**Comment by cmaglie** [comment]
IIRC this was a sf.net mirror, maybe we should host a mirror of the files on the arduino.cc server and keep the original link in the comments.

**Comment by NicoHood** [comment]
sf.net?

Hosting a copy would make sense. But it would also be nice to get an overview of all available arduino downloads from the arduino server. Could you make this also available somehow?

**Comment by cmaglie** [comment]
> sf.net?

sourceforge.net

BTW I was wrong is not a mirror but the official repository of mpc, that quickly went back online.

At this point I prefer to not copy these files but use the official repo.
