### ISSUE TITLE
Code on main branch no longer builds due to moved dependency - hash 8ed806af1d739132c56062d2271a20e5c09a7e7a

### ISSUE THREAD

**Issue by timmattison** [arduino/toolchain-avr#31]
The latest hash as of today - 8ed806af1d739132c56062d2271a20e5c09a7e7a - fails to build because it tries to pull v1.8.0 of avc-libc from http://download.savannah.gnu.org/releases/avr-libc/.  The latest version is available here - http://download.savannah.gnu.org/releases/avr-libc/avr-libc-1.8.1.tar.bz2 - and the 1.8.0 version is available in the old-releases directory here - http://download.savannah.gnu.org/releases/avr-libc/old-releases/avr-libc-1.8.0.tar.bz2

The build script should be updated to use 1.8.0 from the old-releases directory.  I'll create a fork, test that, and follow up here.

**Comment by cmaglie** [comment]
Fixed by #32
