### ISSUE TITLE
Support for ATmega328PB

### ISSUE THREAD

**Issue by awatterott** [arduino/toolchain-avr#36]
The latest Atmel toolchain does not support the new ATmega328**PB**, but the needed files are available from the [ATmega Series Device Support (1.0.98)](http://packs.download.atmel.com).
Can you please add the files (header file, device-specs, avrdude device description) to the next toolchain release?
Here is also an updated header file with the old register/bit naming:
https://github.com/watterott/ATmega328PB-Testing/tree/master/hardware/tools/avr

**Comment by mvcl** [comment]
Please include support for the Atmega328PB support going into the releases. This is a very useful chip, it works well, and has some really helpful added capabilities. I especially appreciate having the second Serial channel. 

Watterott's contributed changes make the ATmega328PB work very well.

**Comment by PaoloP74** [comment]
:+1:

**Comment by gohai** [comment]
Please include support for Atmega328PB.

**Comment by nielsnl68** [comment]
What is the status of this request? I like to start using this chip very soon.

**Comment by facchinm** [comment]
Next toolchain will include 328pb support for sure, alongside 3.6.0 toolchain
