### ISSUE TITLE
Unable to compile on OSX

### ISSUE THREAD

**Issue by kkshmz** [arduino/toolchain-avr#45]
Getting error 
+ gsed -r 's/@itemx/@c @itemx/'
./tools.bash: line 69: gsed: command not found

when trying to download requirements.

**Comment by facchinm** [comment]
HI @kkshmz , you need `gsed` from GNU autotools because the `sed` binary shipped with OSX is not compatible with the script.
The easiest thing to do is downloading it through [homebrew](https://brew.sh/). I'm correcting the readme right now, thanks.

**Comment by facchinm** [comment]
Readme fixed
