### ISSUE TITLE
New toolchain 3.6.0

### ISSUE THREAD

**Issue by salkinium** [arduino/toolchain-avr#46]
--> http://distribute.atmel.no/tools/opensource/Atmel-AVR-GNU-Toolchain/3.6.0

Couldn't find any linux downloads for it though:
http://www.atmel.com/tools/ATMELAVRTOOLCHAINFORLINUX.aspx

**Comment by matthijskooijman** [comment]
Master contains 3.6.1 now, so I think this can be closed.
